/// <reference types="vitest" />
import { defineConfig } from 'vitest/config'
import react from '@vitejs/plugin-react'
import { VitePWA } from 'vite-plugin-pwa'

export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      registerType: 'autoUpdate',
      // Service worker file is generated by Workbox at build time
      workbox: {
        // Cache static assets (JS, CSS, fonts, icons) cache-first
        globPatterns: ['**/*.{js,css,html,ico,png,svg,woff2,woff,webp,jpg,jpeg}'],
        // Network-first for the AI API endpoint (always want fresh responses)
        runtimeCaching: [
          {
            urlPattern: ({ url }: { url: URL }) => url.pathname.startsWith('/api/generate-plan'),
            handler: 'NetworkOnly',
          },
        ],
      },
      manifest: {
        name: 'Revise – Smart Study Planner',
        short_name: 'Revise',
        description: 'AI-powered study plans with spaced repetition and gamification.',
        theme_color: '#FF69B4',
        background_color: '#FFF8F0',
        display: 'standalone',
        orientation: 'portrait',
        start_url: '/',
        scope: '/',
        icons: [
          {
            src: '/icons/icon-192.png',
            sizes: '192x192',
            type: 'image/png',
          },
          {
            src: '/icons/icon-512.png',
            sizes: '512x512',
            type: 'image/png',
          },
          {
            src: '/icons/icon-maskable-512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
        ],
      },
    }),
  ],
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: ['./vitest.setup.ts'],
    environmentOptions: {
      jsdom: {
        url: 'http://localhost',
      },
    },
  },
})
